// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dGeE2L_UY9f2YeD-qkHExioB2iMGwLg',
    appId: '1:888346500388:web:1ec3b5a10bf0d6ddee27b1',
    messagingSenderId: '888346500388',
    projectId: 'sb-note-app',
    authDomain: 'sb-note-app.firebaseapp.com',
    storageBucket: 'sb-note-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0qRxUgiVESbj9tFOEMVFK25HfRU7i914',
    appId: '1:888346500388:android:9d9c78485b67c517ee27b1',
    messagingSenderId: '888346500388',
    projectId: 'sb-note-app',
    storageBucket: 'sb-note-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRWIuxyr47Sv_f4N-XX_M4TMu3dd8wd5o',
    appId: '1:888346500388:ios:fca2afd4bb9be2c4ee27b1',
    messagingSenderId: '888346500388',
    projectId: 'sb-note-app',
    storageBucket: 'sb-note-app.appspot.com',
    iosClientId: '888346500388-e769u773ou9e04cqv512843auddfu07h.apps.googleusercontent.com',
    iosBundleId: 'com.sb.sbnotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRWIuxyr47Sv_f4N-XX_M4TMu3dd8wd5o',
    appId: '1:888346500388:ios:fca2afd4bb9be2c4ee27b1',
    messagingSenderId: '888346500388',
    projectId: 'sb-note-app',
    storageBucket: 'sb-note-app.appspot.com',
    iosClientId: '888346500388-e769u773ou9e04cqv512843auddfu07h.apps.googleusercontent.com',
    iosBundleId: 'com.sb.sbnotesapp',
  );
}
